- name: create a register
  shell: hostname
  register: host

- name: copy file if host name is same
  become: yes
  copy:
    src: scripts/58/config.txt
    dest: /home/sasmob
  when: host.stdout == 58